-- Generated by dvgen.py gen-dv.
-- DUT input driver.
--
-- Usually edited:
--   Replace the simple "set every input from table v" behavior with protocol
--   tasks, e.g. send_req(), push(), pop(), write_reg(), read_reg().
--
-- Behavior after modification:
--   Testcases should call these higher-level driver functions instead of
--   touching dut.* directly. That keeps protocol timing in one place.

local M = {}

local AXI4Master = require "AXI4MasterV2"
local AXI4Memory = require "AXI4Memory"

-- RTL 在仿真顶层中的完整层级。
local DUT_HIER = "tb_top"


-- 创建 AR/AW 地址通道。
local function make_ax_bundle(prefix, name)
    return ([[
        | valid      => valid
        | ready      => ready
        | bits_id    => id
        | bits_addr  => addr
        | bits_len   => len
        | bits_size  => size
        | bits_burst => burst
        | bits_cache => cache
        | bits_qos   => qos
    ]]):abdl {
        hier = DUT_HIER,
        prefix = prefix,
        name = name,
    }
end


-- 创建 W 写数据通道。
local function make_w_bundle(prefix, name)
    return ([[
        | valid     => valid
        | ready     => ready
        | bits_data => data
        | bits_strb => strb
        | bits_last => last
    ]]):abdl {
        hier = DUT_HIER,
        prefix = prefix,
        name = name,
    }
end


-- 创建 B 写响应通道。
local function make_b_bundle(prefix, name)
    return ([[
        | valid     => valid
        | ready     => ready
        | bits_id   => id
        | bits_resp => resp
    ]]):abdl {
        hier = DUT_HIER,
        prefix = prefix,
        name = name,
    }
end


-- 创建 R 读数据通道。
local function make_r_bundle(prefix, name)
    return ([[
        | valid     => valid
        | ready     => ready
        | bits_id   => id
        | bits_data => data
        | bits_resp => resp
        | bits_last => last
    ]]):abdl {
        hier = DUT_HIER,
        prefix = prefix,
        name = name,
    }
end

-- ============================================================
-- 上游接口 io_mst_*：testbench 扮演 AXI Master
-- ============================================================

local mst_ar = make_ax_bundle("io_mst_ar_", "MST_AR")
local mst_r  = make_r_bundle("io_mst_r_", "MST_R")
local mst_aw = make_ax_bundle("io_mst_aw_", "MST_AW")
local mst_w  = make_w_bundle("io_mst_w_", "MST_W")
local mst_b  = make_b_bundle("io_mst_b_", "MST_B")

local axi_master = AXI4Master(
    -- 组件实例名。
    -- 主要用于调度任务名称、事件名称和日志前缀；当环境中存在多个
    -- AXI Master 时，每个实例应使用不同名称，方便定位报错和波形。
    "axi_master",

    -- AXI4MasterV2 构造函数的通道参数顺序固定为 AR、R、AW、W、B。
    -- 这些 AliasBundle 已绑定到 DUT 的 io_mst_* 接口：
    --   mst_ar：Master 发送读地址请求；
    --   mst_r ：Master 接收读数据响应；
    --   mst_aw：Master 发送写地址请求；
    --   mst_w ：Master 发送写数据；
    --   mst_b ：Master 接收写响应。
    mst_ar,
    mst_r,
    mst_aw,
    mst_w,
    mst_b,

    {
        -- AXI Master 上层事务状态机使用的时钟句柄。
        -- read/write 任务的状态推进、超时计数以及完成回调都以该时钟
        -- 的上升沿为基准。这里必须与 AxiReorder 的 AXI 时钟一致。
        clock_chdl = dut.clock:chdl(),

        -- 最多允许 AXI4MasterV2 同时管理的读写事务数量。
        -- 每个未完成事务会占用一个 task slot，完成后才会释放。
        -- 非阻塞 read()/write() 超过该数量时会返回
        -- "NoTaskIDAvailable"。该值还必须适配 AXI ID 位宽。
        nr_task = 64,

        -- 单个事务允许等待的最大周期数。
        -- 上层状态机在等待 AR/AW/W 发送或 R/B 返回时持续计数；超过
        -- 该值说明事务可能卡死，组件会触发超时检查，避免仿真无限等待。
        timeout_max = 2000000,
        --timeout_max = 2000,


        -- 底层 AXI4MasterAgentV2 的配置。
        -- Agent 内部使用五个独立调度任务驱动/采集 AR、R、AW、W、B，
        -- 因此这里的选项主要影响通道级握手、日志和空闲字段行为。
        agent_options = {
            -- 底层通道 Agent 使用的时钟。
            -- valid/ready 握手、通道延迟和背压均在该时钟上判断。
            clock_chdl = dut.clock:chdl(),

            -- 全局仿真周期计数器句柄。
            -- 主要用于日志时间戳和调试信息，不是 AXI 协议信号。
            cycles_chdl = dut.cycles:chdl(),

            -- 是否打印 Agent 的详细事务/通道日志。
            -- false 可保持冒烟日志简洁；调试握手或超时时可临时改为 true。
            verbose = true,

            -- 是否在一个通道事务完成后随机改写非握手 payload 字段。
            -- true 有助于发现 DUT 错误依赖 valid=0 时 payload 的问题，但会让
            -- 波形更杂乱；基础冒烟使用 false，使空闲期信号保持更可预测。
            -- valid 和 ready 本身不会被这个选项随机化。
            enable_randomize_fields = true,
            nr_ar_taskbuf = 64,
            nr_aw_taskbuf = 64,
            nr_w_taskbuf = 64,

            enable_ar_delay = false,
            ar_delay_min = 1,
            ar_delay_range = 5,

            enable_aw_delay = false,
            aw_delay_min = 1,
            aw_delay_range = 5,

            enable_w_delay = false,
            w_delay_min = 1,
            w_delay_range = 3,

            -- 反压
            enable_r_delay = true,
            r_delay_min = 20,
            r_delay_range = 20,

            enable_b_delay = true,
            b_delay_min = 20,
            b_delay_range = 20,

            random_delay = true,
        },
    }
)


-- ============================================================
-- 下游接口 io_slv_*：testbench 扮演 AXI Slave
-- ============================================================

local slv_ar = make_ax_bundle("io_slv_ar_", "SLV_AR")
local slv_r  = make_r_bundle("io_slv_r_", "SLV_R")
local slv_aw = make_ax_bundle("io_slv_aw_", "SLV_AW")
local slv_w  = make_w_bundle("io_slv_w_", "SLV_W")
local slv_b  = make_b_bundle("io_slv_b_", "SLV_B")


local pending_resps = {}

-- 测试阶段调用这个函数，为指定事务安排响应
function M.inject_resp(rule)
    assert(rule.resp >= 0 and rule.resp <= 3)
    pending_resps[#pending_resps + 1] = rule
end

local function resp_hook(ch, addr, id, len, size, burst)
    for i, rule in ipairs(pending_resps) do
        local matched =
            rule.ch == ch and
            (rule.addr  == nil or rule.addr  == addr) and
            (rule.id    == nil or rule.id    == id) and
            (rule.len   == nil or rule.len   == len) and
            (rule.size  == nil or rule.size  == size) and
            (rule.burst == nil or rule.burst == burst)

        if matched then
            table.remove(pending_resps, i)
            return rule.resp
        end
    end

    return 0 -- 未匹配的事务返回 OKAY
end


local axi_memory = AXI4Memory(
    -- 下游 AXI Slave/Memory 组件的实例名。
    -- 用于后台任务名称、事件名称以及日志前缀；环境中存在多个下游
    -- Memory 时应保证名称唯一，便于区分每个端口的事务和报错。
    "axi_memory",

    -- AXI4Memory 构造函数的通道参数顺序固定为 AR、R、AW、W、B。
    -- 这些 AliasBundle 已绑定到 DUT 的 io_slv_* 接口：
    --   slv_ar：Memory 接收 DUT 发出的读地址；
    --   slv_r ：Memory 向 DUT 返回读数据；
    --   slv_aw：Memory 接收 DUT 发出的写地址；
    --   slv_w ：Memory 接收 DUT 发出的写数据；
    --   slv_b ：Memory 向 DUT 返回写响应。
    slv_ar,
    slv_r,
    slv_aw,
    slv_w,
    slv_b,

    {
        -- AXI Memory 五个通道进行 valid/ready 握手时使用的时钟。
        -- 接收请求、访问参考内存以及发送响应都以该时钟上升沿为基准，
        -- 因此必须与 AxiReorder 的 io_slv_* 接口处于同一时钟域。
        clock_chdl = dut.clock:chdl(),

        -- 全局仿真周期计数器。
        -- 组件用它生成日志时间戳、计算配置的通道延迟和判断响应何时就绪；
        -- 它只是验证环境的辅助计数器，不属于 AXI 接口。
        cycles_chdl = dut.cycles:chdl(),

        -- 记录当前 AXI 接口的数据宽度意图：256 bit，即每拍 32 字节。
        -- 当前 AXI4Memory 实现还会通过 slv_r.data:get_width() 读取实际
        -- RDATA 宽度，并据此建立内部 Memory，因此 AliasBundle 连接的真实
        -- 信号宽度必须与这里的配置一致；该选项不能转换总线宽度。
        data_width = 256,

        -- 0=OKAY, 1=EXOKAY, 2=SLVERR, 3=DECERR
        resp_hook = resp_hook,

        -- 是否打印 AXI Memory 的详细通道和内存访问日志。
        -- false 适合日常回归；排查地址、ID、响应延迟时可临时设为 true。
        verbose = false,

        -- 是否在响应完成或通道空闲时随机改写非握手 payload 字段。
        -- true 可检查 DUT 是否错误使用 valid=0 时的 R/B payload；false 可使
        -- 冒烟波形保持稳定清晰。valid/ready 不由这个选项直接随机化。
        enable_randomize_fields = true,

        -- 以下五个开关分别控制各 AXI 通道是否插入延迟。
        -- 全部关闭时，Memory 尽快接收请求并返回响应，适合作为基础冒烟；
        -- 打开后可以模拟下游等待和响应延迟，验证 DUT 的握手保持与背压处理。

        -- random_delay 是整个 AXI4Memory 共用的随机模式开关，也会影响已经启用延迟的 AR/AW/W/B 通道。
        random_delay = true,

        -- AR：读地址接收延迟。开启后不会始终立即拉高 ARREADY。
        enable_ar_delay = true,
        ar_delay_min = 20,
        ar_delay_range = 20,

        -- AW：写地址接收延迟。开启后可推迟 AWREADY 和写地址握手。
        enable_aw_delay = true,
        aw_delay_min = 20,
        aw_delay_range = 20,

        -- W：写数据接收延迟。开启后可推迟 WREADY，向 DUT 施加写数据背压。
        enable_w_delay = true,
        w_delay_min = 20,
        w_delay_range = 20,

        -- R：读响应发送延迟。开启后可推迟 RVALID/各拍读数据返回；
        -- 后续 read-reorder 测试会重点使用该开关和 shuffle_r 等配置。
        enable_r_delay = true,

        -- enable_r_delay未开启时，r_delay_min/r_delay_range 不生效。
        -- 控制延迟是固定值r_delay_min还是随机值(r_delay_min,r_delay_min + r_delay_range)。
        -- R 响应的最小延迟周期数。
        r_delay_min = 100,
        -- R 响应的随机延迟范围。实际延迟周期数 = r_delay_min + [0, r_delay_range]。
        r_delay_range = 100,

        -- 控制“有多笔待读事务时，先选择哪一笔返回”。shuffle_r = true使得有乱序返回的可能。
        shuffle_r = true,

        -- 控制“有多笔待读事务时，先选择哪一笔返回”。shuffle_b = true使得有乱序返回的可能。
        shuffle_b = true,


        -- B：写响应发送延迟。开启后可推迟 BVALID，模拟下游写响应延迟。
        enable_b_delay = true,
        b_delay_min = 100,
        b_delay_range = 100,

        -- nr_b_taskbuf = 4,
        -- nr_r_taskbuf = 1,
        -- nr_w_taskbuf = 64

    }
)

local initialized = false

function M.initialize()
    -- 避免 testcase 重复调用时启动两份后台任务。
    if initialized then
        return
    end

    initialized = true
    axi_master:initialize()
    axi_memory:initialize()
end

-- AXI burst 类型编码。
local BURST_INCR = 1

-- AxiReorder 的数据宽度是 256 bit：
-- 256 bit = 32 byte = 2^5 byte，因此 AxSIZE = 5。
local AXI_SIZE_32_BYTES = 5

-- 256-bit 数据共有 32 个字节，每个字节对应一个 WSTRB bit。
-- 32 个 strobe bit 用 8 个十六进制字符表示。
local FULL_STRB_256 = "ffffffff"


-- 执行一笔单拍阻塞写。
--
-- 参数：
--   addr     ：写地址
--   data_hex ：256-bit 数据，用 64 个十六进制字符表示
--
-- 返回：
--   "Success" 或组件返回的错误字符串
function M.write_single(addr, data_hex)
    assert(
        type(data_hex) == "string",
        "write data must be a hexadecimal string"
    )

    assert(
        #data_hex == 64,
        string.format(
            "256-bit write data must contain 64 hex characters, got %d",
            #data_hex
        )
    )

    return axi_master:block_write(
        addr,
        BURST_INCR,

        -- AxLEN = 实际拍数 - 1。
        -- len=0 表示只有一拍。
        0,

        -- 每拍传输 2^5=32 字节。
        AXI_SIZE_32_BYTES,

        -- block_write 支持 burst，所以数据和 strobe 都用数组传入。
        -- 当前只有一拍，因此数组中各有一个元素。
        { data_hex },
        { FULL_STRB_256 }
    )
end

-- 执行一笔非阻塞写。
function M.noblock_write(addr, burst, len, size, data_hex_vec, strb_hex_vec, axid, qos, cache)

    local ticket = {
        done = false,
        result = nil,
        error = nil,
    }
    assert(type(addr) == "number", "addr must be a number")
    assert(type(burst) == "number", "burst must be a number")
    assert(type(len) == "number", "len must be a number")
    assert(type(size) == "number", "size must be a number")
    assert(type(data_hex_vec) == "table", "data_hex_vec must be a table")
    assert(type(strb_hex_vec) == "table", "strb_hex_vec must be a table")
    assert(type(axid) == "number", "axid must be a number")
    assert(len >= 0 and len <= 255,
        "len must be in range 0..255")
    assert(size >= 0 and size <= 5,
        "size must be in range 0..5")
    assert(
        axid >= 0 and axid < 4096,
        "axid must be in range 0..4095")

    assert(
        #data_hex_vec == len + 1,
        "write data beat count must equal len + 1"
    )

    assert(
        #strb_hex_vec == len + 1,
        "write strobe beat count must equal len + 1"
    )

    for beat, data in ipairs(data_hex_vec) do
        assert(type(data) == "string",
            string.format("data beat %d must be a string", beat))
        assert(#data == 64,
            string.format("data beat %d must contain 64 hex characters", beat))
        assert(data:match("^[0-9a-fA-F]+$"),
            string.format("data beat %d contains invalid hex characters", beat))
    end

    for beat, strb in ipairs(strb_hex_vec) do
        assert(type(strb) == "string",
            string.format("strb beat %d must be a string", beat))
        assert(#strb == 8,
            string.format("strb beat %d must contain 8 hex characters", beat))
        assert(strb:match("^[0-9a-fA-F]+$"),
            string.format("strb beat %d contains invalid hex characters", beat))
    end

    local ret = axi_master:write(
        addr,
        burst,

        -- len = 实际拍数 - 1。
        len,

        -- 每拍传输 2^size 字节。
        size,

        -- write() 使用数组描述每一拍数据和WSTRB。
        -- 数组元素数量必须等于 len + 1。
        data_hex_vec,
        strb_hex_vec,
        {
            axid = axid,
            qos = qos,
            cache = cache,
            finish_callback = function(task)

                ticket.result = {
                    addr = task.addr,
                    axid = task.axid,
                    len = task.len,
                    size = task.size,
                    burst = task.burst,
                }
                ticket.done = true
            end,
        }
    )
    if ret ~= "Success" then
        ticket.error = ret
    end
    return ret, ticket
end

-- 执行一笔单拍阻塞读。
--
-- 返回两个值：
--   ret      ："Success" 或错误字符串
--   data_hex ：读取到的 256-bit 十六进制字符串
function M.read_single(addr)
    local read_data_hex = nil

    local ret = axi_master:block_read(
        addr,
        BURST_INCR,
        0,
        AXI_SIZE_32_BYTES,

        {
            -- AXI4MasterV2 会在读事务结束时调用这个函数。
            -- task.read_data_hex_str_vec 中每个元素对应一拍 RDATA。
            finish_callback = function(task)
                read_data_hex = task.read_data_hex_str_vec[1]
            end,
        }
    )

    return ret, read_data_hex
end

-- 执行一笔非阻塞读。
--
-- 参数：
--   addr ：读地址
--   axid ：上游 AXI ARID
--
-- 返回：
--   ret    ：事务提交结果
--   ticket ：异步结果对象
function M.noblock_read(addr, burst, len, size, axid, qos, cache)

    assert(type(addr) == "number", "addr must be a number")
    assert(type(burst) == "number", "burst must be a number")
    assert(type(len) == "number", "len must be a number")
    assert(type(size) == "number", "size must be a number")
    assert(type(axid) == "number", "axid must be a number")

    assert(axid >= 0 and axid < 4096,
        "axid must be in range 0..4095")
    assert(len >= 0 and len <= 255,
        "len must be in range 0..255")
    assert(size >= 0 and size <= 5,
        "size must be in range 0..5 for a 256-bit bus")

    -- table 按引用传递。函数返回后，完成回调仍可更新其中的字段。
    local ticket = {
        done = false, -- 是否收到完整读响应
        data_vec = nil,   -- 读数据
        result = nil,   
        error = nil,
    }

    local ret = axi_master:read(
        addr,
        burst,
        len,
        size,

        {
            axid = axid,
            qos = qos,
            cache = cache,
            -- AXI4MasterV2 会在读事务结束时调用这个函数。
            -- task.read_data_hex_str_vec 中每个元素对应一拍 RDATA。
            finish_callback = function(task)
                --AXI4MasterV2 完成 callback 后会释放并清空 task。
                --AXI4MasterV2 会在 callback 后复用内部 task，
                --因此这里复制数据，避免 ticket 引用随后被清空的内部数组。
                local data_vec = {}

                for i, data in ipairs(task.read_data_hex_str_vec) do
                    data_vec[i] = data
                end

                -- 保存所有RDATA，方便后续检查；单拍读时只取第一个元素。
                ticket.data_vec = data_vec
                ticket.result = {
                    addr = task.addr,
                    axid = task.axid,
                    len = task.len,
                    size = task.size,
                    burst = task.burst,
                }

                -- done 最后赋值，保证看到 done=true 时其他结果已经有效。
                ticket.done = true
            end,
        }
    )
    if ret ~= "Success" then
        ticket.error = ret
    end
    return ret, ticket
end



function M.drive(v)

    assert(
        not initialized,
        "M.drive() cannot be used after AXI agents are initialized"
    )

    v = v or {}
    dut.io_mst_aw_valid:set(v.io_mst_aw_valid or 0)
    dut.io_mst_aw_bits_id:set(v.io_mst_aw_bits_id or 0)
    dut.io_mst_aw_bits_addr:set(v.io_mst_aw_bits_addr or 0)
    dut.io_mst_aw_bits_len:set(v.io_mst_aw_bits_len or 0)
    dut.io_mst_aw_bits_size:set(v.io_mst_aw_bits_size or 0)
    dut.io_mst_aw_bits_burst:set(v.io_mst_aw_bits_burst or 0)
    dut.io_mst_aw_bits_lock:set(v.io_mst_aw_bits_lock or 0)
    dut.io_mst_aw_bits_cache:set(v.io_mst_aw_bits_cache or 0)
    dut.io_mst_aw_bits_prot:set(v.io_mst_aw_bits_prot or 0)
    dut.io_mst_aw_bits_qos:set(v.io_mst_aw_bits_qos or 0)
    dut.io_mst_aw_bits_region:set(v.io_mst_aw_bits_region or 0)
    dut.io_mst_ar_valid:set(v.io_mst_ar_valid or 0)
    dut.io_mst_ar_bits_id:set(v.io_mst_ar_bits_id or 0)
    dut.io_mst_ar_bits_addr:set(v.io_mst_ar_bits_addr or 0)
    dut.io_mst_ar_bits_len:set(v.io_mst_ar_bits_len or 0)
    dut.io_mst_ar_bits_size:set(v.io_mst_ar_bits_size or 0)
    dut.io_mst_ar_bits_burst:set(v.io_mst_ar_bits_burst or 0)
    dut.io_mst_ar_bits_lock:set(v.io_mst_ar_bits_lock or 0)
    dut.io_mst_ar_bits_cache:set(v.io_mst_ar_bits_cache or 0)
    dut.io_mst_ar_bits_prot:set(v.io_mst_ar_bits_prot or 0)
    dut.io_mst_ar_bits_qos:set(v.io_mst_ar_bits_qos or 0)
    dut.io_mst_ar_bits_region:set(v.io_mst_ar_bits_region or 0)
    dut.io_mst_w_valid:set(v.io_mst_w_valid or 0)
    dut.io_mst_w_bits_data:set(v.io_mst_w_bits_data or 0)
    dut.io_mst_w_bits_strb:set(v.io_mst_w_bits_strb or 0)
    dut.io_mst_w_bits_last:set(v.io_mst_w_bits_last or 0)
    dut.io_mst_b_ready:set(v.io_mst_b_ready or 0)
    dut.io_mst_r_ready:set(v.io_mst_r_ready or 0)
    dut.io_slv_aw_ready:set(v.io_slv_aw_ready or 0)
    dut.io_slv_ar_ready:set(v.io_slv_ar_ready or 0)
    dut.io_slv_w_ready:set(v.io_slv_w_ready or 0)
    dut.io_slv_b_valid:set(v.io_slv_b_valid or 0)
    dut.io_slv_b_bits_id:set(v.io_slv_b_bits_id or 0)
    dut.io_slv_b_bits_resp:set(v.io_slv_b_bits_resp or 0)
    dut.io_slv_r_valid:set(v.io_slv_r_valid or 0)
    dut.io_slv_r_bits_id:set(v.io_slv_r_bits_id or 0)
    dut.io_slv_r_bits_data:set(v.io_slv_r_bits_data or 0)
    dut.io_slv_r_bits_resp:set(v.io_slv_r_bits_resp or 0)
    dut.io_slv_r_bits_last:set(v.io_slv_r_bits_last or 0)
end

return M
