-- Generated by dvgen.py gen-dv.
-- DUT output monitor.
--
-- Usually edited:
--   Convert raw output signal samples into transaction records. For example,
--   only return a transaction when out_valid/out_ready is true.
--
-- Behavior after modification:
--   scoreboards and debug logs become transaction-level instead of raw-cycle
--   signal dumps.

local signals = require "dut.signals"
local cfg = require "cfg"

local M = {}
local subscribers = {}

-- 下游Slave接口上的ID并不是上游AXI ID，而是AxiReorder分配的重排表项号。
-- 读、写通路各自拥有一套独立的重排表，所以这里分别记录已被Slave接收、
-- 但尚未收到最终响应的读表项和写表项。table的key是重排表项ID，value是
-- 首次接收该事务的采样周期，既用于判断表项是否仍被占用，也用于断言报错时
-- 给出前一笔事务的起始周期，方便从波形中定位问题。
local slave_read_outstanding = {}
local slave_write_outstanding = {}

-- 订阅者列表。monitor是唯一读取DUT端口的模块；scoreboard、日志器等
-- 消费者都从这里取得同一份采样结果，避免各模块自行读取端口而造成采样
-- 时刻不一致。当前scoreboard.lua会在加载时注册M.observe回调。
function M.subscribe(callback)
    assert(type(callback) == "function", "monitor subscriber must be a function")
    subscribers[#subscribers + 1] = callback
end

-- 判断一个AXI通道是否在当前采样周期完成了valid/ready握手。只有握手成功
-- 才表示Slave真正接收了请求或DUT真正接收了响应；单独出现valid不能改变
-- 在途状态，否则通道发生反压时会被重复记录。
local function channel_fired(channel)
    return channel.valid == 1 and channel.ready == 1
end

local function clear_slave_outstanding()
    -- reset可能在任意事务阶段到来。复位时逐项清空monitor保存的状态，使复位
    -- 释放后的第一笔事务不会与复位前已经取消的事务产生误报。
    for id in pairs(slave_read_outstanding) do
        slave_read_outstanding[id] = nil
    end
    for id in pairs(slave_write_outstanding) do
        slave_write_outstanding[id] = nil
    end
end

local function check_slave_entry_id_reuse(sample)
    if sample.reset == 1 then
        clear_slave_outstanding()
        return
    end

    local slv_ar = sample.io.slv_ar
    local slv_aw = sample.io.slv_aw
    local slv_r = sample.io.slv_r
    local slv_b = sample.io.slv_b

    -- 先处理本拍完成的响应，再检查本拍新接收的地址请求。这样当旧事务的
    -- RLAST/B与新事务在同一个时钟沿握手时，该表项已经完成，可以合法复用，
    -- 不会被monitor误判成两笔未完成事务占用了同一表项。
    if channel_fired(slv_r) and slv_r.bits.last == 1 then
        slave_read_outstanding[slv_r.bits.id] = nil
    end
    if channel_fired(slv_b) then
        slave_write_outstanding[slv_b.bits.id] = nil
    end

    -- AR握手后，对应读表项必须一直保持占用，直到相同表项ID的最后一个
    -- R beat（RVALID && RREADY && RLAST）完成握手。若占用期间Slave再次
    -- 接收相同表项ID，说明AxiReorder提前复用了尚未完成的读重排表项。
    if channel_fired(slv_ar) then
        local id = slv_ar.bits.id
        local previous_cycle = slave_read_outstanding[id]
        assert(previous_cycle == nil, string.format(
            "slave AR accepted reorder entry id %s at cycle %s, but the read transaction accepted at cycle %s has not completed with an RLAST handshake",
            tostring(id), tostring(sample.cycles), tostring(previous_cycle)
        ))
        slave_read_outstanding[id] = sample.cycles
    end

    -- AW握手后，对应写表项必须一直保持占用，直到相同表项ID的B响应完成
    -- BVALID && BREADY握手。若在此之前再次接收相同表项ID，说明AxiReorder
    -- 提前复用了尚未完成的写重排表项。读写表独立，因此不会跨AR/AW误报。
    if channel_fired(slv_aw) then
        local id = slv_aw.bits.id
        local previous_cycle = slave_write_outstanding[id]
        assert(previous_cycle == nil, string.format(
            "slave AW accepted reorder entry id %s at cycle %s, but the write transaction accepted at cycle %s has not completed with a B handshake",
            tostring(id), tostring(sample.cycles), tostring(previous_cycle)
        ))
        slave_write_outstanding[id] = sample.cycles
    end
end

local function check_internal(sample)
    if sample.reset == 1 then return end

    local ar = sample.internal.ar
    local aw = sample.internal.aw

    -- AR有效时，仲裁器选择的表项必须确实满足发送条件
    if sample.io.slv_ar.valid == 1 then
        local selected = ar.selected_entry
        assert(ar.entries[selected].can_send)
        assert(sample.io.slv_ar.bits.id == selected)
    end

    -- AW队首存在时，nid为0才允许产生下游AWVALID
    if aw.head_valid == 1 then
        local head = aw.entries[aw.head_entry]
        local expected_valid = head.nid == 0 and 1 or 0
        assert(sample.io.slv_aw.valid == expected_valid)

        if sample.io.slv_aw.valid == 1 then
            assert(sample.io.slv_aw.bits.id == aw.head_entry)
        end
    end
end

local function publish(sample)
    -- sample在本拍已完整采集。按注册顺序同步通知消费者，使scoreboard
    -- 能在同一拍同时看到输入端和输出端的valid/ready握手。
    for _, callback in ipairs(subscribers) do
        callback(sample)
    end
end

function M.sample(cycles)
    if not cfg.enable_monitor then
        return nil
    end

    local sample = {
        -- Common state
        cycles = cycles,
        reset = signals.reset:get(),

        -- 所有AXI端口都收纳在io表中：
        --   sample.io.mst_aw.ready
        --   sample.io.mst_aw.bits.id
        -- 通道名与DUT信号中的io_mst_aw_/io_slv_aw_前缀一一对应。
        io = {
            -- 上游Master侧写地址通道。
            mst_aw = {
                ready = signals.io_mst_aw_ready:get(),
                valid = signals.io_mst_aw_valid:get(),
                bits = {
                    id = signals.io_mst_aw_bits_id:get(),
                    addr = signals.io_mst_aw_bits_addr:get(),
                    len = signals.io_mst_aw_bits_len:get(),
                    size = signals.io_mst_aw_bits_size:get(),
                    burst = signals.io_mst_aw_bits_burst:get(),
                    lock = signals.io_mst_aw_bits_lock:get(),
                    cache = signals.io_mst_aw_bits_cache:get(),
                    prot = signals.io_mst_aw_bits_prot:get(),
                    qos = signals.io_mst_aw_bits_qos:get(),
                    region = signals.io_mst_aw_bits_region:get(),
                },
            },

            -- 上游Master侧读地址通道。
            mst_ar = {
                ready = signals.io_mst_ar_ready:get(),
                valid = signals.io_mst_ar_valid:get(),
                bits = {
                    id = signals.io_mst_ar_bits_id:get(),
                    addr = signals.io_mst_ar_bits_addr:get(),
                    len = signals.io_mst_ar_bits_len:get(),
                    size = signals.io_mst_ar_bits_size:get(),
                    burst = signals.io_mst_ar_bits_burst:get(),
                    lock = signals.io_mst_ar_bits_lock:get(),
                    cache = signals.io_mst_ar_bits_cache:get(),
                    prot = signals.io_mst_ar_bits_prot:get(),
                    qos = signals.io_mst_ar_bits_qos:get(),
                    region = signals.io_mst_ar_bits_region:get(),
                },
            },

            -- 上游Master侧写数据、写响应和读响应通道。
            mst_w = {
                ready = signals.io_mst_w_ready:get(),
                valid = signals.io_mst_w_valid:get(),
                bits = {
                    data = signals.io_mst_w_bits_data:get_hex_str(),
                    strb = signals.io_mst_w_bits_strb:get_hex_str(),
                    last = signals.io_mst_w_bits_last:get(),
                },
            },
            mst_b = {
                ready = signals.io_mst_b_ready:get(),
                valid = signals.io_mst_b_valid:get(),
                bits = {
                    id = signals.io_mst_b_bits_id:get(),
                    resp = signals.io_mst_b_bits_resp:get(),
                },
            },
            mst_r = {
                ready = signals.io_mst_r_ready:get(),
                valid = signals.io_mst_r_valid:get(),
                bits = {
                    id = signals.io_mst_r_bits_id:get(),
                    data = signals.io_mst_r_bits_data:get_hex_str(),
                    resp = signals.io_mst_r_bits_resp:get(),
                    last = signals.io_mst_r_bits_last:get(),
                },
            },

            -- 下游Slave侧写地址和读地址通道。
            slv_aw = {
                ready = signals.io_slv_aw_ready:get(),
                valid = signals.io_slv_aw_valid:get(),
                bits = {
                    id = signals.io_slv_aw_bits_id:get(),
                    addr = signals.io_slv_aw_bits_addr:get(),
                    len = signals.io_slv_aw_bits_len:get(),
                    size = signals.io_slv_aw_bits_size:get(),
                    burst = signals.io_slv_aw_bits_burst:get(),
                    lock = signals.io_slv_aw_bits_lock:get(),
                    cache = signals.io_slv_aw_bits_cache:get(),
                    prot = signals.io_slv_aw_bits_prot:get(),
                    qos = signals.io_slv_aw_bits_qos:get(),
                    region = signals.io_slv_aw_bits_region:get(),
                },
            },
            slv_ar = {
                ready = signals.io_slv_ar_ready:get(),
                valid = signals.io_slv_ar_valid:get(),
                bits = {
                    id = signals.io_slv_ar_bits_id:get(),
                    addr = signals.io_slv_ar_bits_addr:get(),
                    len = signals.io_slv_ar_bits_len:get(),
                    size = signals.io_slv_ar_bits_size:get(),
                    burst = signals.io_slv_ar_bits_burst:get(),
                    lock = signals.io_slv_ar_bits_lock:get(),
                    cache = signals.io_slv_ar_bits_cache:get(),
                    prot = signals.io_slv_ar_bits_prot:get(),
                    qos = signals.io_slv_ar_bits_qos:get(),
                    region = signals.io_slv_ar_bits_region:get(),
                },
            },

            -- 下游Slave侧写数据、写响应和读响应通道。
            slv_w = {
                ready = signals.io_slv_w_ready:get(),
                valid = signals.io_slv_w_valid:get(),
                bits = {
                    data = signals.io_slv_w_bits_data:get_hex_str(),
                    strb = signals.io_slv_w_bits_strb:get_hex_str(),
                    last = signals.io_slv_w_bits_last:get(),
                },
            },
            slv_b = {
                ready = signals.io_slv_b_ready:get(),
                valid = signals.io_slv_b_valid:get(),
                bits = {
                    id = signals.io_slv_b_bits_id:get(),
                    resp = signals.io_slv_b_bits_resp:get(),
                },
            },
            slv_r = {
                ready = signals.io_slv_r_ready:get(),
                valid = signals.io_slv_r_valid:get(),
                bits = {
                    id = signals.io_slv_r_bits_id:get(),
                    data = signals.io_slv_r_bits_data:get_hex_str(),
                    resp = signals.io_slv_r_bits_resp:get(),
                    last = signals.io_slv_r_bits_last:get(),
                },
            },
        },

        internal = {
            ar = {
                selected_entry = signals.dbg_ar.selected_entry:get(),
                entries = {},
            },
            aw = {
                head_valid = signals.dbg_aw.head_valid:get(),
                head_ready = signals.dbg_aw.head_ready:get(),
                head_entry = signals.dbg_aw.head_entry:get(),
                entries = {},
            },
        },
        
        
    }

    for i = 0, 63 do
        local ar = signals.dbg_ar.entries[i]
        local aw = signals.dbg_aw.entries[i]

        local ar_valid = ar.valid:get()
        local ar_nid = ar.nid:get()
        local ar_sent = ar.have_sent:get()

        sample.internal.ar.entries[i] = {
            valid = ar_valid,
            id = ar.id:get(),
            addr = ar.addr:get(),
            nid = ar_nid,
            have_sent = ar_sent,
            alloc_hit = ar.alloc_hit:get(),
            -- 等价于RTL中的arShouldSend条件，对4个表项都适用
            can_send = ar_valid == 1 and ar_nid == 0 and ar_sent == 0,
        }

        sample.internal.aw.entries[i] = {
            valid = aw.valid:get(),
            id = aw.id:get(),
            nid = aw.nid:get(),
            have_sent = aw.have_sent:get(),
            alloc_hit = aw.alloc_hit:get(),
        }

        
    end
    check_slave_entry_id_reuse(sample)
    check_internal(sample)


    if cfg.verbose_monitor then
        -- TODO: print useful transaction-level information
    end

    -- 返回值留给调试用途；正常验证由订阅回调自动把sample送到scoreboard，
    -- testcase无需手工传递端口信号。
    publish(sample)
    return sample
end

return M