-- Generated by dvgen.py gen-dv.
-- DUT scoreboard/checker.
--
-- Usually edited:
--   This file is the main module-specific correctness logic. Add reference
--   models, expected queues, assertions, and reset-state checks here.
--
-- Behavior after modification:
--   Failing checks should call assert(false, "...") or assert(condition, "...").
--   xmake run/vcsall will then fail at the first detected mismatch.

local monitor = require "dut.monitor"
local M = {}

-- 自动透传检查的请求方向：mst_aw/mst_ar/mst_w是上游Master送入DUT的
-- 请求，slv_aw/slv_ar/slv_w是DUT送往下游Memory的请求。输入握手会形成
-- 一条期望记录，之后对应输出握手必须按队列顺序取出并逐字段比较。
-- AW/AR故意不比较id：AxiReorder会分配下游id，响应时再还原上游id。
local AUTO_PATHS = {
    { source = "mst_aw", sink = "slv_aw", fields = {
        "addr", "len", "size", "burst", "lock", "cache", "prot", "qos", "region",
    } },
    { source = "mst_ar", sink = "slv_ar", fields = {
        "addr", "len", "size", "burst", "lock", "cache", "prot", "qos", "region",
    } },
    { source = "mst_w", sink = "slv_w", fields = { "data", "strb", "last" } },
}

-- auto_pending按输出通道保存尚未观察到的期望事务。下游可以重排不同ID的
-- 请求或响应，因此这些记录不是FIFO队列：每次握手会按字段搜索匹配项。
local auto_pending = {}
-- 下游B/R响应携带的是AxiReorder分配的id。以下映射将其还原为原始上游id，
-- 用于检查响应没有被送到错误的上游事务。
local write_id_map = {}
local read_id_map = {}

-- AXI4通道 
local CHANNELS = {
    mst_aw = {
        valid = "io_mst_aw_valid",
        ready = "io_mst_aw_ready",
        fields = {
            id = "io_mst_aw_bits_id",
            addr = "io_mst_aw_bits_addr",
            len = "io_mst_aw_bits_len",
            size = "io_mst_aw_bits_size",
            burst = "io_mst_aw_bits_burst",
            lock = "io_mst_aw_bits_lock",
            cache = "io_mst_aw_bits_cache",
            prot = "io_mst_aw_bits_prot",
            qos = "io_mst_aw_bits_qos",
            region = "io_mst_aw_bits_region",
        },
    },

    slv_aw = {
        valid = "io_slv_aw_valid",
        ready = "io_slv_aw_ready",
        fields = {
            id = "io_slv_aw_bits_id",
            addr = "io_slv_aw_bits_addr",
            len = "io_slv_aw_bits_len",
            size = "io_slv_aw_bits_size",
            burst = "io_slv_aw_bits_burst",
            lock = "io_slv_aw_bits_lock",
            cache = "io_slv_aw_bits_cache",
            prot = "io_slv_aw_bits_prot",
            qos = "io_slv_aw_bits_qos",
            region = "io_slv_aw_bits_region",
        },
    },

    mst_ar = {
        valid = "io_mst_ar_valid",
        ready = "io_mst_ar_ready",
        fields = {
            id = "io_mst_ar_bits_id",
            addr = "io_mst_ar_bits_addr",
            len = "io_mst_ar_bits_len",
            size = "io_mst_ar_bits_size",
            burst = "io_mst_ar_bits_burst",
            lock = "io_mst_ar_bits_lock",
            cache = "io_mst_ar_bits_cache",
            prot = "io_mst_ar_bits_prot",
            qos = "io_mst_ar_bits_qos",
            region = "io_mst_ar_bits_region",
        },
    },

    slv_ar = {
        valid = "io_slv_ar_valid",
        ready = "io_slv_ar_ready",
        fields = {
            id = "io_slv_ar_bits_id",
            addr = "io_slv_ar_bits_addr",
            len = "io_slv_ar_bits_len",
            size = "io_slv_ar_bits_size",
            burst = "io_slv_ar_bits_burst",
            lock = "io_slv_ar_bits_lock",
            cache = "io_slv_ar_bits_cache",
            prot = "io_slv_ar_bits_prot",
            qos = "io_slv_ar_bits_qos",
            region = "io_slv_ar_bits_region",
        },
    },

    mst_w = {
        valid = "io_mst_w_valid",
        ready = "io_mst_w_ready",
        fields = {
            data = "io_mst_w_bits_data",
            strb = "io_mst_w_bits_strb",
            last = "io_mst_w_bits_last",
        },
    },

    slv_w = {
        valid = "io_slv_w_valid",
        ready = "io_slv_w_ready",
        fields = {
            data = "io_slv_w_bits_data",
            strb = "io_slv_w_bits_strb",
            last = "io_slv_w_bits_last",
        },
    },

    mst_r = {
        valid = "io_mst_r_valid",
        ready = "io_mst_r_ready",
        fields = {
            id = "io_mst_r_bits_id",
            data = "io_mst_r_bits_data",
            resp = "io_mst_r_bits_resp",
            last = "io_mst_r_bits_last",
        },
    },

    slv_r = {
        valid = "io_slv_r_valid",
        ready = "io_slv_r_ready",
        fields = {
            id = "io_slv_r_bits_id",
            data = "io_slv_r_bits_data",
            resp = "io_slv_r_bits_resp",
            last = "io_slv_r_bits_last",
        },
    },

    mst_b = {
        valid = "io_mst_b_valid",
        ready = "io_mst_b_ready",
        fields = {
            id = "io_mst_b_bits_id",
            resp = "io_mst_b_bits_resp",
        },
    },

    slv_b = {
        valid = "io_slv_b_valid",
        ready = "io_slv_b_ready",
        fields = {
            id = "io_slv_b_bits_id",
            resp = "io_slv_b_bits_resp",
        },
    },
}

-- 保存事务检查状态
local check_enabled = false
local check_name = nil
local expected_queues = {}
local observed_counts = {}
-- 保存持续状态检查规则。
--
-- 与expected_queues不同：
--   expected_queues只在AXI valid && ready握手时检查；
--   expected_states会在每次observe(sample)时检查。
local expected_states = {}

-- 开始检查，设置开关check_enabled并清空状态
function M.begin_check(name)
    assert(not check_enabled, "scoreboard check already active")

    -- 清除上一次检查留下的事务期望。
    check_enabled = true
    check_name = name or "unnamed check"
    expected_queues = {}
    observed_counts = {}

    -- 清除上一次检查留下的状态期望。
    expected_states = {}
end

local function copy_table(source)
    local result = {}

    for key, value in pairs(source) do
        result[key] = value
    end

    return result
end

function M.expect(channel_name, expected)
    assert(check_enabled, "scoreboard check has not started")
    assert(CHANNELS[channel_name],
        "unknown scoreboard channel: " .. tostring(channel_name))
    assert(type(expected) == "table",
        "expected transaction must be a table")

    local queue = expected_queues[channel_name]
    if queue == nil then
        queue = {}
        expected_queues[channel_name] = queue
    end

    queue[#queue + 1] = copy_table(expected)
end

-- 注册一条持续状态检查规则。
--
-- 参数：
--   name      ：规则名称，用于错误日志。
--   condition ：函数，返回true时才检查本规则。
--   expected  ：需要比较的sample字段；未填写的字段不检查。
--   options   ：可选配置：
--                 skip_matches：跳过前几次匹配；
--                 min_checks  ：结束前至少成功检查多少次。
--
-- 示例：
--   scoreboard.expect_state(
--       "outputs inactive during reset",
--       function(sample)
--           return sample.reset == 1
--       end,
--       {
--           io_slv_aw_valid = 0,
--           io_slv_w_valid = 0,
--       },
--       {
--           skip_matches = 1,
--           min_checks = 1,
--       }
--   )
function M.expect_state(name, condition, expected, options)
    assert(
        check_enabled,
        "scoreboard check has not started"
    )
    assert(
        type(name) == "string",
        "state check name must be a string"
    )
    assert(
        type(condition) == "function",
        "state check condition must be a function"
    )
    assert(
        type(expected) == "table",
        "expected state must be a table"
    )

    options = options or {}

    expected_states[#expected_states + 1] = {
        name = name,
        condition = condition,

        -- 复制期望值，防止testcase之后修改原table。
        expected = copy_table(expected),

        -- reset刚拉高的第一拍可能尚未经过有效复位沿，
        -- 因此允许跳过最开始的若干匹配。
        skip_matches = options.skip_matches or 0,

        -- end_check时确认这条规则确实执行过，
        -- 防止因为condition从未成立而产生假通过。
        min_checks = options.min_checks or 1,

        -- condition成立的总次数，包括被跳过的次数。
        match_count = 0,

        -- 实际执行并通过比较的次数。
        check_count = 0,
    }
end

-- 对一条状态规则进行字段比较。
--
-- expected中只写需要检查的字段：
--   { io_slv_aw_valid = 0 }
--
-- 没写的sample字段全部忽略。
local function compare_state(rule, sample)
    for field, expected_value in pairs(rule.expected) do
        local actual_value = sample[field]

        -- 字段不存在通常表示monitor.lua没有采集该信号，
        -- 或者testcase写错了字段名。
        assert(
            actual_value ~= nil,
            string.format(
                "state check '%s': sample does not contain field '%s'",
                rule.name,
                tostring(field)
            )
        )

        assert(
            actual_value == expected_value,
            string.format(
                "state check '%s' field %s mismatch: " ..
                "expected=%s actual=%s cycle=%s",
                rule.name,
                tostring(field),
                tostring(expected_value),
                tostring(actual_value),
                tostring(sample.cycles)
            )
        )
    end
end


local function compare_transaction(
    channel_name,
    transaction_index,
    channel,
    sample,
    expected
)
    for field, expected_value in pairs(expected) do
        local sample_field = channel.fields[field]

        assert(
            sample_field ~= nil,
            string.format(
                "%s does not contain field '%s'",
                channel_name,
                tostring(field)
            )
        )

        local actual_value = sample[sample_field]

        assert(
            actual_value == expected_value,
            string.format(
                "\n\n\n-------------------------ERROR-----------------------------------\n"..
                "%s transaction %d field %s mismatch: " ..
                "expected=%s actual=%s cycle=%s"..
                "\n----------------------------------------------------------------------\n\n\n",
                channel_name,
                transaction_index,
                field,
                tostring(expected_value),
                tostring(actual_value),
                tostring(sample.cycles)
            )
        )
    end
end

local function channel_fired(channel_name, sample)
    local channel = CHANNELS[channel_name]
    return sample[channel.valid] == 1 and sample[channel.ready] == 1
end

local function reset_auto_check()
    -- reset取消所有未完成AXI事务。旧记录不能跨reset沿继续匹配，否则
    -- reset后的首笔事务可能被误与reset前事务比较。
    auto_pending = {}
    write_id_map = {}
    read_id_map = {}
end

local function auto_enqueue(path, sample)
    if not channel_fired(path.source, sample) then
        return
    end

    local source = CHANNELS[path.source]
    local fields = {}
    for _, field in ipairs(path.fields) do
        fields[field] = sample[source.fields[field]]
    end

    local pending = auto_pending[path.sink]
    if pending == nil then
        pending = {}
        auto_pending[path.sink] = pending
    end

    -- source_id只由AW/AR响应路由使用。W通道没有id，此项为nil，但保留
    -- 统一记录结构以减少各通道处理分支。
    pending[#pending + 1] = {
        source_id = sample[source.fields.id],
        fields = fields,
    }
end

local function auto_compare(channel_name, expected, sample)
    local channel = CHANNELS[channel_name]

    for field, expected_value in pairs(expected.fields) do
        local actual_value = sample[channel.fields[field]]
        assert(
            actual_value == expected_value,
            string.format(
                "%s automatic check field %s mismatch: expected=%s actual=%s cycle=%s",
                channel_name,
                field,
                tostring(expected_value),
                tostring(actual_value),
                tostring(sample.cycles)
            )
        )
    end
end

local function auto_take_matching(sink, sample)
    if not channel_fired(sink, sample) then
        return nil
    end

    local pending = auto_pending[sink]
    local channel = CHANNELS[sink]
    local expected = nil

    if pending ~= nil then
        for index, candidate in ipairs(pending) do
            local matched = true

            for field, expected_value in pairs(candidate.fields) do
                if sample[channel.fields[field]] ~= expected_value then
                    matched = false
                    break
                end
            end

            if matched then
                expected = table.remove(pending, index)
                break
            end
        end
    end

    assert(
        expected ~= nil,
        string.format(
            "%s has no matching expected transaction at cycle %s",
            sink,
            tostring(sample.cycles)
        )
    )
    auto_compare(sink, expected, sample)
    return expected
end

local function auto_check_responses(sample)
    -- 先处理响应，再处理同拍新请求。下游id可能在旧响应完成的同一拍
    -- 被重新分配；先删除旧映射可避免把新AW/AR误判为id冲突。
    if channel_fired("slv_b", sample) then
        local downstream_id = tostring(sample.io_slv_b_bits_id)
        local upstream_id = write_id_map[downstream_id]
        assert(
            upstream_id ~= nil,
            string.format(
                "slv_b response for unknown downstream id %s at cycle %s",
                downstream_id,
                tostring(sample.cycles)
            )
        )
        write_id_map[downstream_id] = nil
        auto_pending.mst_b = auto_pending.mst_b or {}
        auto_pending.mst_b[#auto_pending.mst_b + 1] = {
            fields = {
                id = upstream_id,
                resp = sample.io_slv_b_bits_resp,
            },
        }
    end

    if channel_fired("slv_r", sample) then
        local downstream_id = tostring(sample.io_slv_r_bits_id)
        local route = read_id_map[downstream_id]
        assert(
            route ~= nil,
            string.format(
                "slv_r response for unknown downstream id %s at cycle %s",
                downstream_id,
                tostring(sample.cycles)
            )
        )
        auto_pending.mst_r = auto_pending.mst_r or {}
        auto_pending.mst_r[#auto_pending.mst_r + 1] = {
            fields = {
                id = route.upstream_id,
                data = sample.io_slv_r_bits_data,
                resp = sample.io_slv_r_bits_resp,
                last = sample.io_slv_r_bits_last,
            },
        }
        if sample.io_slv_r_bits_last == 1 then
            read_id_map[downstream_id] = nil
        end
    end

    auto_take_matching("mst_b", sample)
    auto_take_matching("mst_r", sample)
end

local function observe_auto(sample)
    -- B/R方向是slv输入、mst输出，先把下游响应转换成上游期望。
    auto_check_responses(sample)

    -- AW/AR/W方向是mst输入、slv输出：先记录输入，再消费输出。即便简单
    -- DUT在同拍透传，也会先建立期望再进行比较。
    for _, path in ipairs(AUTO_PATHS) do
        auto_enqueue(path, sample)
    end

    for _, path in ipairs(AUTO_PATHS) do
        local expected = auto_take_matching(path.sink, sample)
        if expected ~= nil and path.sink == "slv_aw" then
            local downstream_id = tostring(sample.io_slv_aw_bits_id)
            assert(write_id_map[downstream_id] == nil,
                "downstream write id reused before its response: " .. downstream_id)
            write_id_map[downstream_id] = expected.source_id
        elseif expected ~= nil and path.sink == "slv_ar" then
            local downstream_id = tostring(sample.io_slv_ar_bits_id)
            assert(read_id_map[downstream_id] == nil,
                "downstream read id reused before its last response: " .. downstream_id)
            read_id_map[downstream_id] = { upstream_id = expected.source_id }
        end
    end
end

-- 每个采样周期执行一次所有状态规则。
local function observe_states(sample)
    for _, rule in ipairs(expected_states) do
        -- condition决定当前sample是否属于这条规则。
        if rule.condition(sample) then
            rule.match_count = rule.match_count + 1

            -- 例如reset拉高的第一拍可能不稳定，可以跳过。
            if rule.match_count > rule.skip_matches then
                compare_state(rule, sample)
                rule.check_count = rule.check_count + 1
            end
        end
    end
end

function M.observe(sample)
    if sample == nil then
        return
    end

    if sample.reset == 1 then
        reset_auto_check()
        if check_enabled then
            observe_states(sample)
        end
        return
    end

    -- 自动checker始终开启，不依赖testcase侧begin_check()/expect()调用。
    -- begin_check系列接口仍保留给复位状态等不能由输入推导的专用规则。
    observe_auto(sample)

    if not check_enabled then
        return
    end

    observe_states(sample)

    for channel_name, queue in pairs(expected_queues) do
        local channel = CHANNELS[channel_name]

        local fire =
            sample[channel.valid] == 1 and
            sample[channel.ready] == 1

        if fire then
            local expected = table.remove(queue, 1)

            assert(
                expected ~= nil,
                string.format(
                    "unexpected %s transaction at cycle %s",
                    channel_name,
                    tostring(sample.cycles)
                )
            )

            local index = (observed_counts[channel_name] or 0) + 1
            observed_counts[channel_name] = index

            compare_transaction(
                channel_name,
                index,
                channel,
                sample,
                expected
            )
        end
    end
end

-- 由tc_main在所有testcase任务结束后统一调用。它检查队列为空和下游ID
-- 映射全部回收，从而发现“输入握手成功但输出丢失或响应未返回”的错误。
function M.finish_auto_check()
    for channel_name, pending in pairs(auto_pending) do
        assert(
            #pending == 0,
            string.format(
                "automatic check ended with %d unobserved %s transactions",
                #pending,
                channel_name
            )
        )
    end

    for downstream_id in pairs(write_id_map) do
        assert(false,
            "automatic check ended with pending write response for downstream id " ..
            downstream_id)
    end
    for downstream_id in pairs(read_id_map) do
        assert(false,
            "automatic check ended with pending read response for downstream id " ..
            downstream_id)
    end
end

function M.end_check()
    assert(check_enabled, "scoreboard check has not started")

    for channel_name, queue in pairs(expected_queues) do
        assert(
            #queue == 0,
            string.format(
                "%s ended with %d unobserved transactions",
                channel_name,
                #queue
            )
        )
    end

    -- 确认所有状态规则都真正执行过。
    --
    -- 如果condition从未成立，check_count就是0。
    -- 此时不能让测试通过，否则reset可能根本没有拉高。
    for _, rule in ipairs(expected_states) do
        assert(
            rule.check_count >= rule.min_checks,
            string.format(
                "state check '%s' ran only %d times, expected at least %d",
                rule.name,
                rule.check_count,
                rule.min_checks
            )
        )
    end

    print(string.format(
        "Scoreboard check passed: %s",
        check_name
    ))

    check_enabled = false
    check_name = nil
end

function M.check_smoke()
    -- TODO: check basic DUT behavior

end

-- scoreboard加载完成后注册为monitor消费者。这里不会形成循环依赖：
-- monitor只保存回调，不会反向require scoreboard。
monitor.subscribe(M.observe)

return M
