-- Generated by dvgen.py gen-dv.
-- Signal handle table created from the parsed RTL top-module ports.
--
-- Usually edited:
--   If the Verilua-generated testbench instance is not u_Top, rerun
--   gen-dv with --hier <instance> or update the dut.<hier> paths below.
--
-- Behavior after modification:
--   driver.lua, monitor.lua, and env.lua use these handles. A wrong
--   path here causes runtime signal lookup failures or stale sampling.

local M = {}

M.clock = dut.clock:chdl()
M.reset = dut.reset:chdl()
M.io_mst_aw_ready = dut.io_mst_aw_ready:chdl()
M.io_mst_aw_valid = dut.io_mst_aw_valid:chdl()
M.io_mst_aw_bits_id = dut.io_mst_aw_bits_id:chdl()
M.io_mst_aw_bits_addr = dut.io_mst_aw_bits_addr:chdl()
M.io_mst_aw_bits_len = dut.io_mst_aw_bits_len:chdl()
M.io_mst_aw_bits_size = dut.io_mst_aw_bits_size:chdl()
M.io_mst_aw_bits_burst = dut.io_mst_aw_bits_burst:chdl()
M.io_mst_aw_bits_lock = dut.io_mst_aw_bits_lock:chdl()
M.io_mst_aw_bits_cache = dut.io_mst_aw_bits_cache:chdl()
M.io_mst_aw_bits_prot = dut.io_mst_aw_bits_prot:chdl()
M.io_mst_aw_bits_qos = dut.io_mst_aw_bits_qos:chdl()
M.io_mst_aw_bits_region = dut.io_mst_aw_bits_region:chdl()
M.io_mst_ar_ready = dut.io_mst_ar_ready:chdl()
M.io_mst_ar_valid = dut.io_mst_ar_valid:chdl()
M.io_mst_ar_bits_id = dut.io_mst_ar_bits_id:chdl()
M.io_mst_ar_bits_addr = dut.io_mst_ar_bits_addr:chdl()
M.io_mst_ar_bits_len = dut.io_mst_ar_bits_len:chdl()
M.io_mst_ar_bits_size = dut.io_mst_ar_bits_size:chdl()
M.io_mst_ar_bits_burst = dut.io_mst_ar_bits_burst:chdl()
M.io_mst_ar_bits_lock = dut.io_mst_ar_bits_lock:chdl()
M.io_mst_ar_bits_cache = dut.io_mst_ar_bits_cache:chdl()
M.io_mst_ar_bits_prot = dut.io_mst_ar_bits_prot:chdl()
M.io_mst_ar_bits_qos = dut.io_mst_ar_bits_qos:chdl()
M.io_mst_ar_bits_region = dut.io_mst_ar_bits_region:chdl()
M.io_mst_w_ready = dut.io_mst_w_ready:chdl()
M.io_mst_w_valid = dut.io_mst_w_valid:chdl()
M.io_mst_w_bits_data = dut.io_mst_w_bits_data:chdl()
M.io_mst_w_bits_strb = dut.io_mst_w_bits_strb:chdl()
M.io_mst_w_bits_last = dut.io_mst_w_bits_last:chdl()
M.io_mst_b_ready = dut.io_mst_b_ready:chdl()
M.io_mst_b_valid = dut.io_mst_b_valid:chdl()
M.io_mst_b_bits_id = dut.io_mst_b_bits_id:chdl()
M.io_mst_b_bits_resp = dut.io_mst_b_bits_resp:chdl()
M.io_mst_r_ready = dut.io_mst_r_ready:chdl()
M.io_mst_r_valid = dut.io_mst_r_valid:chdl()
M.io_mst_r_bits_id = dut.io_mst_r_bits_id:chdl()
M.io_mst_r_bits_data = dut.io_mst_r_bits_data:chdl()
M.io_mst_r_bits_resp = dut.io_mst_r_bits_resp:chdl()
M.io_mst_r_bits_last = dut.io_mst_r_bits_last:chdl()
M.io_slv_aw_ready = dut.io_slv_aw_ready:chdl()
M.io_slv_aw_valid = dut.io_slv_aw_valid:chdl()
M.io_slv_aw_bits_id = dut.io_slv_aw_bits_id:chdl()
M.io_slv_aw_bits_addr = dut.io_slv_aw_bits_addr:chdl()
M.io_slv_aw_bits_len = dut.io_slv_aw_bits_len:chdl()
M.io_slv_aw_bits_size = dut.io_slv_aw_bits_size:chdl()
M.io_slv_aw_bits_burst = dut.io_slv_aw_bits_burst:chdl()
M.io_slv_aw_bits_lock = dut.io_slv_aw_bits_lock:chdl()
M.io_slv_aw_bits_cache = dut.io_slv_aw_bits_cache:chdl()
M.io_slv_aw_bits_prot = dut.io_slv_aw_bits_prot:chdl()
M.io_slv_aw_bits_qos = dut.io_slv_aw_bits_qos:chdl()
M.io_slv_aw_bits_region = dut.io_slv_aw_bits_region:chdl()
M.io_slv_ar_ready = dut.io_slv_ar_ready:chdl()
M.io_slv_ar_valid = dut.io_slv_ar_valid:chdl()
M.io_slv_ar_bits_id = dut.io_slv_ar_bits_id:chdl()
M.io_slv_ar_bits_addr = dut.io_slv_ar_bits_addr:chdl()
M.io_slv_ar_bits_len = dut.io_slv_ar_bits_len:chdl()
M.io_slv_ar_bits_size = dut.io_slv_ar_bits_size:chdl()
M.io_slv_ar_bits_burst = dut.io_slv_ar_bits_burst:chdl()
M.io_slv_ar_bits_lock = dut.io_slv_ar_bits_lock:chdl()
M.io_slv_ar_bits_cache = dut.io_slv_ar_bits_cache:chdl()
M.io_slv_ar_bits_prot = dut.io_slv_ar_bits_prot:chdl()
M.io_slv_ar_bits_qos = dut.io_slv_ar_bits_qos:chdl()
M.io_slv_ar_bits_region = dut.io_slv_ar_bits_region:chdl()
M.io_slv_w_ready = dut.io_slv_w_ready:chdl()
M.io_slv_w_valid = dut.io_slv_w_valid:chdl()
M.io_slv_w_bits_data = dut.io_slv_w_bits_data:chdl()
M.io_slv_w_bits_strb = dut.io_slv_w_bits_strb:chdl()
M.io_slv_w_bits_last = dut.io_slv_w_bits_last:chdl()
M.io_slv_b_ready = dut.io_slv_b_ready:chdl()
M.io_slv_b_valid = dut.io_slv_b_valid:chdl()
M.io_slv_b_bits_id = dut.io_slv_b_bits_id:chdl()
M.io_slv_b_bits_resp = dut.io_slv_b_bits_resp:chdl()
M.io_slv_r_ready = dut.io_slv_r_ready:chdl()
M.io_slv_r_valid = dut.io_slv_r_valid:chdl()
M.io_slv_r_bits_id = dut.io_slv_r_bits_id:chdl()
M.io_slv_r_bits_data = dut.io_slv_r_bits_data:chdl()
M.io_slv_r_bits_resp = dut.io_slv_r_bits_resp:chdl()
M.io_slv_r_bits_last = dut.io_slv_r_bits_last:chdl()


-- 模块内部信号
local core = dut.u_AxiReorder

M.dbg_ar = {
    selected_entry = core["_selSendAR_arb_io_chosen"]:chdl(), -- AR仲裁器本拍选择的表项号
    entries = {},
}

M.dbg_aw = {
    head_valid = core["_awq_io_deq_valid"]:chdl(),       -- AW队列是否存在队首
    head_ready = core.awq_io_deq_ready:chdl(),           -- AW队首本拍是否允许出队
    head_entry = core["_awq_io_deq_bits_entry"]:chdl(),  -- AW队首对应的重排表项号
    entries = {},
}

for i = 0, 63 do
    M.dbg_ar.entries[i] = {
        valid = core["rvld_" .. i]:chdl(), -- AR重排表项有效位
        id = core["arinfo_" .. i .. "_bits_id"]:chdl(), -- 保存的上游ARID
        addr = core["arinfo_" .. i .. "_bits_addr"]:chdl(), -- 保存的AR地址
        nid = core["arinfo_" .. i .. "_nid"]:chdl(), -- 此事务之前同ID未完成数量
        have_sent = core["arinfo_" .. i .. "_haveSendAR"]:chdl(), -- AR是否已发往下游
        alloc_hit = core["ar_mst_fire_hit_" .. i]:chdl(), -- 本拍新AR是否分配给该表项
    }

    M.dbg_aw.entries[i] = {
        valid = core["wvld_" .. i]:chdl(), -- AW重排表项有效位
        id = core["awinfo_" .. i .. "_id"]:chdl(), -- 保存的上游AWID
        nid = core["awinfo_" .. i .. "_nid"]:chdl(), -- 此事务之前同ID未完成数量
        have_sent = core["awinfo_" .. i .. "_haveSendAW"]:chdl(), -- AW是否已发往下游
        alloc_hit = core["aw_mst_fire_hit_" .. i]:chdl(), -- 本拍新AW是否分配给该表项
    }
end





return M
