-- Generated by dvgen.py init-chisel.
-- Generic testcase dispatcher.
--
-- Usually edited:
--   Almost never. Keep this file as the common test runner.
--
-- Behavior:
--   xmake.lua selects test_cases/NNN_name.lua and exports TC_NAME.
--   This file requires that testcase, resets DUT, starts monitor, runs each
--   task in tc.tasks, then finishes the simulation.

local env = require "env"
local tc_name = assert(os.getenv "TC_NAME", "failed to get TC_NAME")

fork {
    main_task = function()
        if os.getenv "DUMP" then
            sim.dump_wave((os.getenv "TC" or "sim") .. ".vcd")
        end

        local tc = require(tc_name)

        env.dut_reset()
        env.launch_monitor_task()

        for _, task in ipairs(tc.tasks) do
            task()
        end

        env.test_success()
        sim.finish()
    end
}
