---@diagnostic disable: undefined-global, undefined-field

-- ============================================================================
-- Generated by dvgen.py init-chisel.
--
-- Usually edited fields:
--   1. mill target/main below in target("rtl")
--      This AxiInfra Chisel project exposes `test.runMain`, and its Scala
--      generator object is `generator.LmssGenerator`. If a later Chisel project
--      uses different names, update these two strings; that changes which Scala
--      generator `xmake r rtl` invokes.
--   2. cfg.top in target("sim")
--      This project emits AxiSubsysTop.sv. If the generator is changed to emit a
--      different top module later, update cfg.top and rerun gen-dv with the same
--      --top value.
--
-- Usually kept stable:
--   src/common, src/dut, test_cases, and the shortcut tasks at the bottom.
-- ============================================================================

local prj_dir = os.projectdir()
local build_dir = path.join(prj_dir, "build")
local rtl_dir = path.join(build_dir, "rtl")
local chisel_dir = path.join(prj_dir, "ChiselTemplate")
local src_dir = path.join(prj_dir, "src")
local tc_dir = path.join(prj_dir, "test_cases")

local sim = os.getenv("SIM") or "vcs"

-- Generate SystemVerilog from ChiselTemplate and copy it into build/rtl.
-- If your Chisel project has a different Mill module or main class, regenerate
-- this file with --mill-target/--main or edit the two string arguments below.
-- After changing them, `xmake r rtl` will invoke the new Chisel entry point.
target("rtl", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        local chisel_rtl_dir = path.join(chisel_dir, "build", "rtl")
        local home_dir = os.getenv("HOME") or "/nfs/home/yanglucheng"
        os.cd(chisel_dir)
        os.execv("mill", {
            "-i",
            "test.runMain",
            "generator.LmssGenerator",
            "--target", "systemverilog",
            "--split-verilog",
            "-td", chisel_rtl_dir
        }, {
            envs = {
                -- This machine's Java reports user.home as "?". Mill/JLine then
                -- tries to load ?/.cache/.../libjlinenative.so and fails before
                -- running the generator. Setting _JAVA_OPTIONS fixes user.home.
                -- If Java is fixed globally later, this line can be removed.
                _JAVA_OPTIONS = "-Duser.home=" .. home_dir,

                -- Force the JVM launcher instead of the native Mill launcher.
                -- This avoids the native launcher's JLine cache path issue on
                -- this host. It only affects this xmake-launched Mill command.
                MILL_VERSION = "1.0.6-jvm"
            }
        })

        os.tryrm(rtl_dir)
        os.mkdir(rtl_dir)
        os.cp(path.join(chisel_rtl_dir, "*"), rtl_dir)
        cprint("${green underline}[INFO]${clear} RTL copied to build/rtl/")
    end)
end)

target("sim", function()
    set_default(true)
    add_rules("verilua")

    if sim == "verilator" then
        add_toolchains("@verilator")
    else
        add_toolchains("@vcs")
    end

    -- Verilua needs both Lua verification files and RTL files in this target.
    -- Add extra RTL directories here if a future generator emits more files.
    -- Changing this list affects what VCS/Verilator compiles for `xmake b sim`.
    add_files(
        path.join(tc_dir, "*.lua"),
        path.join(src_dir, "*.lua"),
        path.join(src_dir, "common", "*.lua"),
        path.join(src_dir, "dut", "*.lua"),
        path.join(rtl_dir, "*.sv"),
        path.join(rtl_dir, "*.v"),
        path.join(rtl_dir, "verification", "*.sv"),
        path.join(rtl_dir, "verification", "assert", "*.sv"),
        path.join(rtl_dir, "verification", "assume", "*.sv"),
        path.join(rtl_dir, "verification", "cover", "*.sv")
    )

    add_values("vcs.flags", "+incdir+" .. path.join(rtl_dir, "verification"))
    set_values("cfg.build_dir_name", "sim")
    -- DUT top module name. If gen-dv parses a different module name, keep this
    -- value consistent with that --top argument or the simulator top will not
    -- match the generated signal paths.
    set_values("cfg.top", "AxiSubsysTop")

    -- TC chooses test_cases/NNN_name.lua by its first three characters.
    -- Example: TC=001 selects test_cases/001_*.lua and exports TC_NAME for
    -- tc_main.lua. Adding a new numbered test file is enough to add a new case.
    local TC = os.getenv("TC")
    if TC then
        TC = TC:sub(1, 3)
    else
        TC = "000"
    end
    local test_cases = os.files(path.join(tc_dir, "*.lua"))
    for _, test_case in ipairs(test_cases) do
        local test_case_file = path.filename(test_case)
        if test_case_file:startswith(TC) then
            add_runenvs("TC_NAME", path.basename(test_case_file))
        end
    end

    set_values("cfg.lua_main", "tc_main.lua")
end)

target("clean", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        os.tryrm(build_dir)
        cprint("${green underline}[INFO]${clear} build/ removed")
    end)
end)

local function _tc_or_default()
    import("core.base.option")
    return option.get("tc") or os.getenv("TC") or "000"
end

-- Wrapper around the real sim target. This avoids duplicating Verilua/VCS build
-- rules in custom tasks. If target("sim") changes later, these tasks inherit it.
local function _run_xmake(action, tc)
    os.execv("xmake", {action, "-P", prj_dir, "sim"}, {envs = {SIM = "vcs", TC = tc}})
end

-- Build only. Equivalent to: SIM=vcs TC=xxx xmake build -P <project> sim
task("vcs", function()
    set_menu {
        usage = "xmake vcs [options]",
        description = "Build sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        _run_xmake("build", _tc_or_default())
    end)
end)

-- Run only. Requires the sim target to have been built already.
-- Equivalent to: SIM=vcs TC=xxx xmake run -P <project> sim
task("simrun", function()
    set_menu {
        usage = "xmake simrun [options]",
        description = "Run sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        _run_xmake("run", _tc_or_default())
    end)
end)

-- Build then run. Use this for the common edit/test loop.
task("vcsall", function()
    set_menu {
        usage = "xmake vcsall [options]",
        description = "Build and run sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        local tc = _tc_or_default()
        _run_xmake("build", tc)
        _run_xmake("run", tc)
    end)
end)

-- Open an FSDB with Verdi. If --fsdb is not provided, the task picks the
-- lexicographically last *.fsdb under build/vcs/sim. If your filenames do not
-- sort by testcase/time, pass -f explicitly.
task("verdi", function()
    set_menu {
        usage = "xmake verdi [options]",
        description = "Open FSDB waveform with Verdi",
        options = {
            {"f", "fsdb", "kv", nil, "fsdb file path"}
        }
    }
    on_run(function()
        import("core.base.option")
        local fsdb = option.get("fsdb")
        if not fsdb then
            local fsdbs = os.files(path.join(build_dir, "vcs", "sim", "*.fsdb"))
            table.sort(fsdbs)
            assert(#fsdbs > 0, "no fsdb found in " .. path.join(build_dir, "vcs", "sim"))
            fsdb = fsdbs[#fsdbs]
        end
        os.execv("verdi", {"-ssf", fsdb})
    end)
end)
