---@diagnostic disable: undefined-global, undefined-field

-- ============================================================================
-- Generated by dvgen.py init-chisel.
--
-- Usually edited fields:
--   1. mill target/main below in target("rtl")
--      This AxiInfra Chisel project exposes `test.runMain`, and its Scala
--      generator object is `generator.LmssGenerator`. If a later Chisel project
--      uses different names, update these two strings; that changes which Scala
--      generator `xmake r rtl` invokes.
--   2. cfg.top in target("sim")
--      This project emits AxiSubsysTop.sv. If the generator is changed to emit a
--      different top module later, update cfg.top and rerun gen-dv with the same
--      --top value.
--
-- Usually kept stable:
--   src/common, src/dut, test_cases, and the shortcut tasks at the bottom.
-- ============================================================================

local prj_dir = os.projectdir()
local build_dir = path.join(prj_dir, "build")
local rtl_dir = path.join(build_dir, "rtl")
local AxiInfra_dir = path.join(prj_dir, "AxiInfra")
local src_dir = path.join(prj_dir, "src")
local tc_dir = path.join(prj_dir, "test_cases")

if os.exists(path.join(AxiInfra_dir, "xmake.lua")) then includes(AxiInfra_dir) end

target("init", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        cprint("${green underline}[INFO] Updating submodules in this repo... This may take a few seconds.${clear}")
        os.exec("git submodule update --init")
        os.cd(AxiInfra_dir)
        cprint("${green underline}[INFO] Updating submodules in submodules... This may take a few seconds.${clear}")
        os.exec("git submodule update --init")
    end)
end)

target("rtl", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        import("core.base.task")
        os.tryrm(path.join(AxiInfra_dir, "build", "*"))
        os.tryrm(path.join(AxiInfra_dir, "out", "*"))
        os.cd(AxiInfra_dir)
        task.run("rtl")
        os.tryrm(rtl_dir)
        os.mkdir(rtl_dir)
        os.cp(path.join(AxiInfra_dir, "build", "rtl", "*"), rtl_dir)
    end)
end)

target("sim", function()
    set_default(true)
    add_rules("verilua")

    add_toolchains("@vcs")

    add_files(
        path.join(tc_dir, "*.lua"),
        path.join(src_dir, "*.lua"),
        path.join(src_dir, "common", "*.lua"),
        path.join(src_dir, "dut", "*.lua"),
        path.join(rtl_dir, "*.sv"),
        path.join(rtl_dir, "*.v"),
        path.join(rtl_dir, "verification", "*.sv"),
        path.join(rtl_dir, "verification", "assert", "*.sv"),
        path.join(rtl_dir, "verification", "assume", "*.sv"),
        path.join(rtl_dir, "verification", "cover", "*.sv")
    )

    set_values("vcs.flags", "-xprop")
    add_values("vcs.flags", "+define+ASSERT_VERBOSE_CO0_test_for_smokeND_=1", "+define+STOP_COND_=1")
    add_values("vcs.flags",
        "+incdir+" .. path.join(rtl_dir, "verification"),
        "+incdir+" .. path.join(rtl_dir, "verification", "assert"),
        "+incdir+" .. path.join(rtl_dir, "verification", "assume"),
        "+incdir+" .. path.join(rtl_dir, "verification", "cover")
    )
    set_values("cfg.build_dir_name", "sim")
    set_values("cfg.top", "AxiSubsysTop")

    local TC = os.getenv("TC")
    if TC then
        TC = TC:sub(1, 3)
    else
        TC = "000"
    end
    local test_cases = os.files(path.join(tc_dir, "*.lua"))
    for _, test_case in ipairs(test_cases) do
        local test_case_file = path.filename(test_case)
        if test_case_file:startswith(TC) then
            add_runenvs("TC_NAME", path.basename(test_case_file))
        end
    end

    set_values("cfg.lua_main", "tc_main.lua")
end)

target("clean", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        os.tryrm(build_dir)
    end)
end)
