-- Generated by dvgen.py gen-dv.
-- Minimal smoke testcase.
--
-- Usually edited:
--   Replace driver.drive({}) with the simplest legal transaction for this DUT.
--   Add more cycles if the DUT has latency.
--
-- Behavior after modification:
--   This file is selected by TC=000. Keep it fast and basic so it can be used
--   as the first sanity check after every RTL regeneration.

local env = require "env"
local driver = require "dut.driver"
local scoreboard = require "dut.scoreboard"

local function task_smoke()
    -- 启动上游 AXI Master 和下游 AXI Memory 的后台任务。
    driver.initialize()

    -- 给组件一个时钟周期完成初始信号驱动。
    env.wait_cycles(1)

    local test_addr = 0x1000

    -- 256 bit 等于 64 个十六进制字符。
    -- 这里特意使用容易在波形中辨认的数据。
    local write_data =
        "00112233445566778899aabbccddeeff" ..
        "fedcba98765432100123456789abcdef"

    -- ========================================================
    -- 第一步：写入 AXI4Memory
    -- ========================================================

    local write_ret = driver.write_single(test_addr, write_data)

    assert(
        write_ret == "Success",
        "\n\n---ERROR---\n\nAXI smoke write failed: " ..
            tostring(write_ret) ..
            "\n\n-----------\n\n"
    )

    -- ========================================================
    -- 第二步：从相同地址读回
    -- ========================================================

    local read_ret, read_data = driver.read_single(test_addr)

    assert(
        read_ret == "Success",
        "\n\n---ERROR---\n\nAXI smoke read failed: " ..
            tostring(read_ret) ..
            "\n\n-----------\n\n"
    )

    assert(
        read_data ~= nil,
        "\n\n---ERROR---\n\nAXI smoke read completed without data\n\n-----------\n\n"
    )

    -- 组件可能返回大写或小写十六进制字符串，
    -- 因此统一转换成小写后比较。
    assert(
        read_data:lower() == write_data:lower(),
        string.format(
            "\n\n---ERROR---\n\nAXI smoke data mismatch:\nexpected: %s\nactual:   %s\n\n-----------\n\n",
            write_data,
            read_data
        )
    )

    print(string.format(
        "AXI smoke read/write passed: addr=0x%x data=%s",
        test_addr,
        read_data
    ))
end

return {
    tasks = {
        task_smoke
    }
}
