//==================================================
// This file contains the Excluded objects
// Generated By User: yanglucheng
// Format Version: 2
// Date: Mon Aug  3 16:48:40 2026
// ExclMode: default
//==================================================
CHECKSUM: "3696433278 437214188"

//u_AxiReorder.awq：AXI AWINFO中的LOCK/REGION/PROT字段未被设计使用，
// 按接口配置固定为常量，因此排除Toggle Coverage。
INSTANCE: tb_top.u_AxiReorder.awq
Toggle io_deq_bits_awinfo_lock "net io_deq_bits_awinfo_lock"
Toggle io_enq_bits_awinfo_region "net io_enq_bits_awinfo_region[3:0]"
Toggle io_enq_bits_awinfo_prot "net io_enq_bits_awinfo_prot[2:0]"
Toggle io_enq_bits_awinfo_lock "net io_enq_bits_awinfo_lock"
Toggle io_deq_bits_awinfo_region "net io_deq_bits_awinfo_region[3:0]"
Toggle io_deq_bits_awinfo_prot "net io_deq_bits_awinfo_prot[2:0]"
CHECKSUM: "1040514739 1772673746"
//
// u_AxiReorder：当前配置不支持AXI LOCK/REGION/PROT属性，
// 相应AR/AW侧带信号固定为常量，不属于本配置的覆盖目标。
INSTANCE: tb_top.u_AxiReorder
Toggle io_mst_ar_bits_lock "net io_mst_ar_bits_lock"
Toggle io_slv_aw_bits_region "net io_slv_aw_bits_region[3:0]"
Toggle io_slv_aw_bits_prot "net io_slv_aw_bits_prot[2:0]"
Toggle io_slv_aw_bits_lock "net io_slv_aw_bits_lock"
Toggle io_slv_ar_bits_region "net io_slv_ar_bits_region[3:0]"
Toggle io_slv_ar_bits_prot "net io_slv_ar_bits_prot[2:0]"
Toggle io_slv_ar_bits_lock "net io_slv_ar_bits_lock"
Toggle io_mst_aw_bits_region "net io_mst_aw_bits_region[3:0]"
Toggle io_mst_aw_bits_prot "net io_mst_aw_bits_prot[2:0]"
Toggle io_mst_aw_bits_lock "net io_mst_aw_bits_lock"
Toggle io_mst_ar_bits_region "net io_mst_ar_bits_region[3:0]"
Toggle io_mst_ar_bits_prot "net io_mst_ar_bits_prot[2:0]"
