---@diagnostic disable: undefined-global, undefined-field

-- ============================================================================
-- Generated by dvgen.py init-chisel.
--
-- Usually edited fields:
--   1. mill target/main below in target("rtl")
--      Change these when the Chisel project uses a different Mill module or
--      Scala GenerateVerilog object. This changes how RTL is produced by
--      `xmake r rtl`.
--   2. cfg.top in target("sim")
--      Change this when the generated RTL top module is not "AxiReorder". This
--      changes which module Verilua asks the simulator to instantiate.
--
-- Usually kept stable:
--   src/common, src/dut, test_cases, and the shortcut tasks at the bottom.
-- ============================================================================

local prj_dir = os.projectdir()
local build_dir = path.join(prj_dir, "build")
local rtl_dir = path.join(build_dir, "rtl")
local chisel_dir = path.join(prj_dir, "ChiselTemplate")
local src_dir = path.join(prj_dir, "src")
local tc_dir = path.join(prj_dir, "test_cases")

-- AXI Master/Slave 公共组件所在目录。
-- test_zhujiang_utils 是一个指向外部组件仓库的软链接。
local axi_component_dir = path.join(
    src_dir,
    "components",
    "AXI",
    "test_zhujiang_utils"
)

local sim = os.getenv("SIM") or "vcs"

-- Generate SystemVerilog from ChiselTemplate and copy it into build/rtl.
-- If your Chisel project has a different Mill module or main class, regenerate
-- this file with --mill-target/--main or edit the two string arguments below.
-- After changing them, `xmake r rtl` will invoke the new Chisel entry point.
target("rtl", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        local chisel_rtl_dir = path.join(chisel_dir, "build", "rtl")
        os.cd(chisel_dir)
        os.execv("mill", {
            "-i",
            "test.runMain",
            "generator.AxiReorderGen",
            "--target", "systemverilog",
            "--split-verilog",
            "-td", chisel_rtl_dir
        })

        os.tryrm(rtl_dir)
        os.mkdir(rtl_dir)
        os.cp(path.join(chisel_rtl_dir, "*"), rtl_dir)
        cprint("${green underline}[INFO]${clear} RTL copied to build/rtl/")
    end)
end)

target("sim", function()
    set_default(true)
    add_rules("verilua")

    if sim == "verilator" then
        add_toolchains("@verilator")
    else
        add_toolchains("@vcs")
    end

    -- Verilua needs both Lua verification files and RTL files in this target.
    -- Add extra RTL directories here if a future generator emits more files.
    -- Changing this list affects what VCS/Verilator compiles for `xmake b sim`.
    add_files(
        path.join(tc_dir, "*.lua"),
        path.join(src_dir, "*.lua"),
        path.join(src_dir, "common", "*.lua"),
        path.join(src_dir, "dut", "*.lua"),
        -- 加入 AXI Master、AXI Memory 和相关工具模块。
        path.join(axi_component_dir, "*.lua"),
        
        path.join(rtl_dir, "*.sv"),
        path.join(rtl_dir, "*.v")
--        path.join(rtl_dir, "verification", "*.sv"),
--        path.join(rtl_dir, "verification", "assert", "*.sv"),
--        path.join(rtl_dir, "verification", "assume", "*.sv"),
--        path.join(rtl_dir, "verification", "cover", "*.sv")
    )

    add_values("vcs.flags", "+incdir+" .. path.join(rtl_dir, "verification"))
    set_values("cfg.build_dir_name", "sim")
    -- DUT top module name. If gen-dv parses a different module name, keep this
    -- value consistent with that --top argument or the simulator top will not
    -- match the generated signal paths.
    set_values("cfg.top", "AxiReorder")

    -- TC chooses test_cases/NNN_name.lua by its first three characters.
    -- Example: TC=001 selects test_cases/001_*.lua and exports TC_NAME for
    -- tc_main.lua. Adding a new numbered test file is enough to add a new case.
    local TC = os.getenv("TC")
    if TC then
        TC = TC:sub(1, 3)
    else
        TC = "000"
    end

    -- ========================================================================
    -- VCS 代码覆盖率
    --
    -- 编译期和运行期均使用固定的 coverage.vdb。编译期将 RTL coverage
    -- shape（源码、行、条件、分支定义）写入该数据库；运行期再把每条
    -- testcase 的命中数据追加到同一数据库。这样 Verdi 可以直接打开它，
    -- 不依赖 URG 合并，也不会打开只有运行数据的空壳 VDB。
    --
    -- `-cm` 必须在编译期和运行期都出现。编译期负责插桩；运行期负责实际
    -- 监控和记录命中。若运行期漏掉 `-cm`，cm.log 会报告
    -- "No VCS Code Coverage Metrics were monitored"。
    --
    -- `-cm_name` 以 TC 区分测试。例如 TC=002 的数据会保存为
    -- coverage.vdb 内的 002 testdata 节点。连续运行 000/001/002 时，
    -- VCS 保留各自记录，Verdi 可查看累计覆盖率并选择具体测试。
    --
    -- 本段仅适用于 VCS；SIM=verilator 时保持原有仿真流程，不添加 VCS
    -- 专用的 `-cm` 参数。
    -- ========================================================================
    if sim == "vcs" then
        local cm_metrics = "line+cond+tgl+fsm+branch+assert"
        local cm_root = path.join(build_dir, "vcs", "sim", "cov")
        local cm_dir = path.join(cm_root, "coverage.vdb")

        -- os.mkdir 不能在 xmake.lua 的配置加载阶段直接调用。构建和运行
        -- 可能被分别执行，因此两个 hook 都确保 coverage.vdb 的父目录存在。
        before_build(function()
            os.mkdir(cm_root)
        end)
        before_run(function()
            os.mkdir(cm_root)
        end)

        -- 编译阶段启用行、条件、翻转、状态机、分支和断言覆盖率，并将
        -- RTL 的静态 coverage shape 写入固定 VDB。
        add_values(
            "vcs.flags",
            "-cm " .. cm_metrics,
            "-cm_dir " .. cm_dir
        )

        -- 运行阶段必须再次声明 `-cm`。VCS 不会因为编译时使用过 -cm 就
        -- 自动在仿真时监控覆盖率；缺少它时 cm.log 会显示 "No VCS Code
        -- Coverage Metrics were monitored"，coverage.vdb 也不会产生命中
        -- 数据。-cm_dir 复用固定 VDB，-cm_name 记录当前 testcase 名称。
        set_values(
            "vcs.run_flags",
            "-cm " .. cm_metrics,
            "-cm_dir " .. cm_dir,
            "-cm_name " .. TC
        )
    end

    local test_cases = os.files(path.join(tc_dir, "*.lua"))
    for _, test_case in ipairs(test_cases) do
        local test_case_file = path.filename(test_case)
        if test_case_file:startswith(TC) then
            add_runenvs("TC_NAME", path.basename(test_case_file))
        end
    end

    set_values("cfg.lua_main", "tc_main.lua")
end)

target("clean", function()
    set_kind("phony")
    set_default(false)
    on_run(function()
        os.tryrm(build_dir)
        cprint("${green underline}[INFO]${clear} build/ removed")
    end)
end)

-- 这里只处理传入值，不在普通 Lua 函数中调用 xmake 的 import。
local function _tc_or_default(tc)
    return tc or os.getenv("TC") or "000"
end

-- Wrapper around the real sim target. This avoids duplicating Verilua/VCS build
-- rules in custom tasks. If target("sim") changes later, these tasks inherit it.
--local function _run_xmake(action, tc)
    --os.execv("xmake", {action, "-P", prj_dir, "sim"}, {envs = {SIM = "vcs", TC = tc}})
--end

-- Build only. Equivalent to: SIM=vcs TC=xxx xmake build -P <project> sim
task("vcs", function()
    set_menu {
        usage = "xmake vcs [options]",
        description = "Build sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        import("core.base.option")

        local tc = _tc_or_default(option.get("tc"))

        os.execv(
            "xmake",
            {"build", "-P", prj_dir, "sim"},
            {
                envs = {
                    SIM = "vcs",
                    TC = tc,
                },
            }
        )
    end)
end)

-- Run only. Requires the sim target to have been built already.
-- Equivalent to: SIM=vcs TC=xxx xmake run -P <project> sim
task("simrun", function()
    set_menu {
        usage = "xmake simrun [options]",
        description = "Run sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        import("core.base.option")

        local tc = _tc_or_default(option.get("tc"))
        os.execv(
            "xmake",
            {"run", "-P", prj_dir, "sim"},
            {
                envs = {
                    SIM = "vcs",
                    TC = tc,
                },
            }
        )
    end)
end)

-- Build then run. Use this for the common edit/test loop.
task("vcsall", function()
    set_menu {
        usage = "xmake vcsall [options]",
        description = "Build and run sim target with VCS",
        options = {
            {"t", "tc", "kv", "000", "test case id, e.g. 000/001/002"}
        }
    }
    on_run(function()
        import("core.base.option")

        local tc = _tc_or_default(option.get("tc"))
--        _run_xmake("build", tc)
--        _run_xmake("run", tc)
        -- 先构建仿真目标。
        os.execv(
            "xmake",
            {"build", "-P", prj_dir, "sim"},
            {envs = {SIM = "vcs", TC = tc}}
        )

        -- 构建成功后运行仿真。
        os.execv(
            "xmake",
            {"run", "-P", prj_dir, "sim"},
            {envs = {SIM = "vcs", TC = tc}}
        )
    end)
end)

-- Open an FSDB with Verdi. If --fsdb is not provided, the task picks the
-- lexicographically last *.fsdb under build/vcs/sim. If your filenames do not
-- sort by testcase/time, pass -f explicitly.
task("verdi", function()
    set_menu {
        usage = "xmake verdi [options]",
        description = "Open FSDB waveform with Verdi",
        options = {
            {"f", "fsdb", "kv", nil, "fsdb file path"}
        }
    }
    on_run(function()
        import("core.base.option")
        local fsdb = option.get("fsdb")
        if not fsdb then
            local fsdbs = os.files(path.join(build_dir, "vcs", "sim", "*.fsdb"))
            table.sort(fsdbs)
            assert(#fsdbs > 0, "no fsdb found in " .. path.join(build_dir, "vcs", "sim"))
            fsdb = fsdbs[#fsdbs]
        end
        os.execv("verdi", {"-ssf", fsdb})
    end)
end)

-- 打开 VCS 代码覆盖率。此 task 与 `xmake verdi` 分工不同：后者查看
-- FSDB 时序波形；本 task 以 `-cov` 直接打开包含 RTL shape 与 testcase
-- 命中数据的 coverage.vdb，显示 RTL 行、条件、分支等覆盖率。
task("verdi_cov", function()
    set_menu {
        usage = "xmake verdi_cov",
        description = "Open cumulative VCS coverage for all recorded testcases"
    }
    on_run(function()
        local cm_root = path.join(build_dir, "vcs", "sim", "cov")
        local vdb = path.join(cm_root, "coverage.vdb")

        -- 所有 testcase 的命中数据都保存在同一个完整 VDB 中。本 task 不
        -- 传 Verdi 的 -tests 筛选参数，因此始终显示所有已运行 testcase
        -- 的累计覆盖率；不需要也不接受 -t 选项。
        -- 缺失 VDB 通常说明尚未执行带覆盖率的 VCS 编译和仿真。
        assert(os.isdir(vdb), "no coverage VDB found: " .. vdb .. "; run xmake vcsall -t <tc> first")
        os.execv("verdi", {"-cov", "-covdir", vdb})
    end)
end)
