-- Generated by dvgen.py init-chisel.
-- Common clock/reset helper.
--
-- Usually edited:
--   Only change this file if your DUT has a non-standard reset sequence
--   (active-low reset, async reset, multiple clocks, multiple resets).
--
-- Behavior after modification:
--   env.dut_reset() calls M.reset(), so reset timing changes here affect every
--   testcase generated by dvgen.

local M = {}

local clock = dut.clock:chdl()
local reset = dut.reset:chdl()

function M.wait_cycles(n)
    clock:posedge(n or 1)
end

function M.reset(cycles)
    reset:set_imm(1)
    clock:posedge(cycles or 10)
    reset:set_imm(0)
end

M.clock = clock
M.reset = reset

return M
