-- Generated by dvgen.py gen-dv.
-- DUT scoreboard/checker.
--
-- Usually edited:
--   This file is the main module-specific correctness logic. Add reference
--   models, expected queues, assertions, and reset-state checks here.
--
-- Behavior after modification:
--   Failing checks should call assert(false, "...") or assert(condition, "...").
--   xmake run/vcsall will then fail at the first detected mismatch.

local M = {}

function M.check_reset()
    -- TODO: check reset state
end

function M.check_smoke()
    -- TODO: check basic DUT behavior
end

return M
