-- Generated by dvgen.py gen-dv.
-- Minimal smoke testcase.
--
-- Usually edited:
--   Replace driver.drive({}) with the simplest legal transaction for this DUT.
--   Add more cycles if the DUT has latency.
--
-- Behavior after modification:
--   This file is selected by TC=000. Keep it fast and basic so it can be used
--   as the first sanity check after every RTL regeneration.

local env = require "env"
local driver = require "dut.driver"
local scoreboard = require "dut.scoreboard"

local function task_smoke()
    driver.drive({})
    env.wait_cycles(1)
    scoreboard.check_smoke()
end

return {
    tasks = {
        env.dut_reset,
        task_smoke
    }
}
