-- Generated by dvgen.py init-chisel.
-- This file contains runtime switches shared by all DUTs.
-- You normally keep this file stable and control behavior with environment
-- variables:
--   ENABLE=0 disables monitor sampling.
--   VER=0 disables verbose monitor printing.
--   HEART=0 disables heartbeat printing if env.lua uses it.

local utils = require "verilua.LuaUtils"

local cfg = {}
local get_env_or_else = utils.get_env_or_else

cfg.enable_monitor = get_env_or_else("ENABLE", "boolean", true)
cfg.verbose_monitor = get_env_or_else("VER", "boolean", true)
cfg.enable_heart_beat = get_env_or_else("HEART", "boolean", true)

return cfg
