-- Generated by dvgen.py gen-dv.
-- DUT environment adapter.
--
-- Usually edited:
--   1. M.drive_default()
--      Set all DUT inputs to legal idle values. This prevents X/unknown state
--      before and after reset.
--   2. monitor_task()
--      Change sampling cadence if your protocol should sample on a different
--      clock edge or only when valid/ready fires.
--   3. M.dut_reset()
--      Change reset length or add post-reset initialization.
--
-- Behavior after modification:
--   Every testcase calls env.dut_reset() and may call env.wait_cycles(), so
--   changes here affect all tests.

local clock_reset = require "common.clock_reset"
local signals = require "dut.signals"
local monitor = require "dut.monitor"
-- 加载scoreboard时，它会向monitor注册observe回调。因此这里不能再写
-- scoreboard.observe(monitor.sample(...))，否则同一个采样会被检查两次。
require "dut.scoreboard"

local M = {}
local monitor_task_id = 0
local has_monitor_task = false

local function monitor_task()
    local cycles = dut.cycles:get()

    while true do
        -- monitor.sample()内部完成端口采样并发布给订阅者；testcase只负责
        -- 产生激励，不需要调用scoreboard。
        monitor.sample(cycles)
        if cycles % 10000 == 0 then
            print("Running...", cycles)
        end
        signals.clock:posedge()
        cycles = cycles + 1
    end
end

function M.drive_default()
    dut.io_mst_aw_valid:set(0)
    dut.io_mst_aw_bits_id:set(0)
    dut.io_mst_aw_bits_addr:set(0)
    dut.io_mst_aw_bits_len:set(0)
    dut.io_mst_aw_bits_size:set(0)
    dut.io_mst_aw_bits_burst:set(0)
    dut.io_mst_aw_bits_lock:set(0)
    dut.io_mst_aw_bits_cache:set(0)
    dut.io_mst_aw_bits_prot:set(0)
    dut.io_mst_aw_bits_qos:set(0)
    dut.io_mst_aw_bits_region:set(0)
    dut.io_mst_ar_valid:set(0)
    dut.io_mst_ar_bits_id:set(0)
    dut.io_mst_ar_bits_addr:set(0)
    dut.io_mst_ar_bits_len:set(0)
    dut.io_mst_ar_bits_size:set(0)
    dut.io_mst_ar_bits_burst:set(0)
    dut.io_mst_ar_bits_lock:set(0)
    dut.io_mst_ar_bits_cache:set(0)
    dut.io_mst_ar_bits_prot:set(0)
    dut.io_mst_ar_bits_qos:set(0)
    dut.io_mst_ar_bits_region:set(0)
    dut.io_mst_w_valid:set(0)
    dut.io_mst_w_bits_data:set(0)
    dut.io_mst_w_bits_strb:set(0)
    dut.io_mst_w_bits_last:set(0)
    dut.io_mst_b_ready:set(0)
    dut.io_mst_r_ready:set(0)
    dut.io_slv_aw_ready:set(0)
    dut.io_slv_ar_ready:set(0)
    dut.io_slv_w_ready:set(0)
    dut.io_slv_b_valid:set(0)
    dut.io_slv_b_bits_id:set(0)
    dut.io_slv_b_bits_resp:set(0)
    dut.io_slv_r_valid:set(0)
    dut.io_slv_r_bits_id:set(0)
    dut.io_slv_r_bits_data:set(0)
    dut.io_slv_r_bits_resp:set(0)
    dut.io_slv_r_bits_last:set(0)
end

function M.dut_reset()
    M.drive_default()
    clock_reset.reset(10)
end

function M.wait_cycles(n)
    clock_reset.wait_cycles(n)
end

function M.launch_monitor_task()
    if not has_monitor_task then
        has_monitor_task = true
        monitor_task_id = scheduler:append_task(nil, "monitor_task", monitor_task, true)
    end
end

function M.test_success()
    print("=== TEST PASSED ===")
    io.flush()
end

return M
